server {
  listen 80;
  server_name 192.168.9.197 211.181.221.197 localhost;

  root /usr/share/nginx/html;
  index index.html;

  # React SPA 라우팅 처리
  location / {
    try_files $uri $uri/ /index.html;
  }

  # 정적 파일 캐싱 (선택 사항)
  location /static/ {
    access_log off;
    expires 1d;
  }
}
